export const isModalShow = state => state.isModalShow
export const navBarCount = state => state.navBarCount
export const item_data = state => state.item_data
export const isMinusShow = state => state.isMinusShow
export const isCartShow = state => state.isCartShow
export const curTabIndex = state => state.tabIndex
export const curItemId = state => state.itemId
export const itemAddedCount = state => state.itemAddedCount
export const orderInfo = state => state.orderInfo
