export const isModalShow = state => state.isModalShow
export const navBarCount = state => state.navBarCount
export const item_data = state => state.item_data
export const isMinusShow = state => state.isMinusShow
export const isCartShow = state => state.isCartShow
export const curTabIndex = state => state.tabIndex
export const curItemId = state => state.itemId
export const itemAddedCount = state => state.itemAddedCount
export const orderInfo = state => state.orderInfo
export const totalMoney = state => state.totalMoney
export const itemConfig = state => state.itemConfig
export const curFuncTab = state => state.curFuncTab
export const configItemAdded = state => state.configItemAdded
export const personalInfo = state => state.personalInfo
export const activityInfo = state => state.activityInfo
export const shopInfo = state => state.shopInfo
export const couponInfo = state => state.couponInfo