/**
 *
 * Created by my on 11/12/16.
 */
export const SHOW_MODAL = 'SHOW_MODAL'

export const SET_NAVBAR_COUNT = 'SET_NAVBAR_COUNT'

export const SET_ITEM_DATA = 'SET_ITEM_DATA'

export const SHOW_MINUS = "SHOW_MINUS"

export const SHOW_CART = "SHOW_CART"

export const SET_TAB_INDEX = "SET_TAB_INDEX"

export const SET_ITEM_ID = "SET_ITEM_ID"

export const SET_ITEM_COUNT = "SET_ITEM_COUNT"

export const SET_ORDER_INFO = "SET_ORDER_INFO"

export const SET_TOTAL_MONEY = "SET_TOTAL_MONEY"

export const SET_ITEM_CONFIG = "SET_ITEM_CONFIG"

export const SET_FUNC_TAB = "SET_FUNC_TAB"

export const SET_FUNC_TAB2 = "SET_FUNC_TAB2"

export const ADD_CONFIG_ITEM_ADDED = "ADD_CONFIG_ITEM_ADDED"

export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO"

export const SET_ACTIVITY_INFO = "SET_ACTIVITY_INFO"

export const SET_SHOP_INFO = "SET_SHOP_INFO"

export const MODIFY_BALANCE = "MODIFY_BALANCE"

export const SET_COUPON_INFO = "SET_COUPON_INFO"

export const SET_HISTORY_ORDER = "SET_HISTORY_ORDER"

export const SET_GOODS_COUNT = "SET_GOODS_COUNT"

export const SET_COUPON_GET = "SET_COUPON_GET"

export const INC_ORDER_INFO = "INC_ORDER_INFO"

export const MINUS_ORDER_INFO = "MINUS_ORDER_INFO"

export const INC_CONFIG_ITEM_COUNT = "INC_CONFIG_ITEM_COUNT"

export const MINUS_CONFIG_ITEM_COUNT = "MINUS_CONFIG_ITEM_COUNT"